---
# defaults file for linux-agent
system_packages:           
  - ca-certificates
  - curl 
  - apt-transport-https
  - lsb-release
  - build-essential
  - checkinstall
  - libreadline-gplv2-dev 
  - libncursesw5-dev 
  - libssl-dev 
  - libsqlite3-dev 
  - tk-dev 
  - libgdbm-dev 
  - libc6-dev 
  - libbz2-dev