---
deployment:
  name: esml-build-agents
  environment: dev
  managed_image_name: 
  location: "westeurope"
  agent_type: "AzureDevOps"

scale_set:
  new_instance: false
  settings:
    resource_group: General_Ben
    name: "ado-agent-lab"

builds:
  target_resource_group: "General_Ben"
  # toggle weither to use location or target resource group
  # for build. This choice depends on RBAC scope.
  use_target_rg_for_build: true
  linux:
    image_publisher: Canonical
    image_offer: 0001-com-ubuntu-server-focal
    image_sku: 20_04-lts-gen2
    vm_size: Standard_B1s
    enable: true
    config:
      gpg_packages:
        - name: docker
          url: https://download.docker.com/linux/ubuntu/gpg
          keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        - name: azure-cli
          url: https://packages.microsoft.com/keys/microsoft.asc
          keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
      repositories:
        - name: docker
          content: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable"
          filename: docker.list
        - name: azure-cli
          content: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_facts.distribution_release }} main"
          filename: azure-cli.list
      packages: []

  windows:
    enable: false
    image_publisher: MicrosoftWindowsServer
    image_offer: WindowsServer
    image_sku: 2022-datacenter
    vm_size: 20348.587.220303
    config:
      image_offer: 2022-datacenter
      powershell_modules:
        - name: Az
          version: latest
      choco_packages:
        - name: git
          version: '2.35.2'
        - name: azure-cli
          version: '2.35.0' 