---
deployment:
  name: devopsagent
  environment: dev
  location: "westeurope"
  agent_type: "AzureDevOps"
  replication: "Standard_LRS"

target_scale_sets:
  # collect all existing virtual machine scale sets that you want to upgrade with 
  # a new image here.
  - name: "vmss-mlmcn-weeu-prod-001"
    resource_group: ml-enterprise-prod-rg
    os_type: linux

builds:
  # where to save images
  target_resource_group: "ml-enterprise-prod-rg"
  gallery:
    enabled: true
    name: gal_mlcmn_weeu_lab_001
    resource_group: ml-enterprise-prod-rg
    publisher: esml
  # toggle weither to use location or target resource group
  # for build. This choice depends on RBAC scope of the service principal that is used.
  use_target_rg_for_build: true
  linux:
    version: '0.0.2'
    image_publisher: Canonical
    image_offer: 0001-com-ubuntu-server-focal-daily
    image_sku: 20_04-daily-lts-gen2
    vm_size: Standard_B1s
    image_definition: esml-devops-agent-linux
    image_hyperv_generation: 2
    enable: true
    config:
      compile_from_source:
        - name: python36
          url: https://www.python.org/ftp/python/3.6.10/Python-3.6.10.tgz
        - name: packages-microsoft-prod
          url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
      install_scripts: 
        - name: miniconda
          url: https://repo.anaconda.com/miniconda/Miniconda3-py39_4.11.0-Linux-x86_64.sh
          checksum: 4ee9c3aa53329cd7a63b49877c0babb49b19b7e5af29807b793a76bdb1d362b4
          installation_args: []
      download_binaries: []
        # - name: 
        #   url: 
        #   dst_folder: 
      gpg_packages:
        - name: azure-cli
          url: https://packages.microsoft.com/keys/microsoft.asc
          keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
      repositories: []
        # - name: 
        #   content: 
        #   filename: 
      packages:
        - name: azure-cli
          version: '*'
        - name: powershell
          version: '*'

  windows:
    enable: false
    version: '0.0.1'
    image_publisher: MicrosoftWindowsServer
    image_offer: WindowsServer
    image_sku: 2022-datacenter
    image_definition: adowindows
    image_hyperv_generation: 2
    vm_size: Standard_B1s
    config:
      image_offer: 2022-datacenter
      powershell_modules:
        - name: Az
          version: latest
      choco_packages:
        - name: git
          version: '2.35.2'
        - name: azure-cli
          version: '2.35.0' 