---
deployment:
  name: devopsagent
  environment: dev
  location: "westeurope"
  agent_type: "AzureDevOps"
  replication: "Standard_LRS"

builds:
  # where to save images
  target_resource_group: "ml-enterprise-dev-rg"
  gallery:
    enabled: true
    name: img_mlcmn_weeu_dev_001
    resource_group: ml-enterprise-dev-rg
    publisher: esml-infra-team
  # toggle weither to use location or target resource group
  # for build. This choice depends on RBAC scope of the service principal that is used.
  use_target_rg_for_build: true
  linux:
    version: '1.0.4'
    image_publisher: Canonical
    image_offer: 0001-com-ubuntu-server-focal-daily
    image_sku: 20_04-daily-lts-gen2
    vm_size: Standard_D2s_v3
    image_definition: esml-devops-agent-linux
    image_hyperv_generation: 2
    enable: true
    roles:
      - name: linux-packages
        vars:
          install_from_source:
            - name: python36
              url: https://www.python.org/ftp/python/3.6.10/Python-3.6.10.tgz
          install_scripts: []
          download_binaries: []
            # - name: 
            #   url: 
            #   dst_folder: 
          gpg_packages: []
            # - name: azure-cli
            #   url: https://packages.microsoft.com/keys/microsoft.asc
            #   keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
          repositories: []
            # - name: azure-cli
            #   content: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_facts.distribution_release }} main
            #   filename. azure-cli.list
          packages: []
            # - name: string
      - name: ado-virtual-machine-scaleset
        vars: {}
      - name: esml
        vars:
          git_repo: https://github.com/jostrm/azure-enterprise-scale-ml.git
          conda_user: AzDevOps
          anaconda_packages:
            - name: anaconda
              url: https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh
              checksum: a7c0afe862f6ea19a596801fc138bde0463abcbce1b753e8d5c474b506a2db2d
              installation_prefix: /home/AzDevOps/anaconda3

  windows:
    enable: false
    version: '0.0.1'
    image_publisher: MicrosoftWindowsServer
    image_offer: WindowsServer
    image_sku: 2022-datacenter
    image_definition: adowindows
    image_hyperv_generation: 2
    vm_size: Standard_B1s
    config:
      image_offer: 2022-datacenter
      powershell_modules:
        - name: Az
          version: latest
      choco_packages:
        - name: git
          version: '2.35.2'
        - name: azure-cli
          version: '2.35.0' 