# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main

pool:
  name: "Azure Pipelines"
  vmImage: 'ubuntu-18.04'

variables:
    # ------ Do change variables below --------
    # See "service connections" under Azure DevOps organization settings
    - name: env
      value: dev

    - name: service_connection
      value: 'azure-devops-demo-sp'

    - name: packer_resource_group_name
      value: "ben-packer-weeu-lab-001"

    - name: location
      value: "westeurope"

    - group: 'service-connection-credentials'

stages:
  - stage: RunPacker
    jobs:
    - job: CreateImage
      steps:
      - task: riezebosch.Packer.PackerTool.PackerTool@0
        displayName: 'Use Packer Latest'

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer version'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/images/AzureDevOps/ado-agents.pkr.hcl'
          command: version

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer init'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/images/AzureDevOps/ado-agents.pkr.hcl'
          command: init

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer validate'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/images/AzureDevOps/ado-agents.pkr.hcl'
          command: validate
          variables-file: '$(Build.Repository.LocalPath)/images/AzureDevOps/ado-agents.auto.pkrvars.hcl'
          variables: 'ansible_playbook_path="$(Build.Repository.LocalPath)/images/AzureDevOps/ansible'    

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer build'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/images/AzureDevOps/ado-agents.pkr.hcl'
          variables-file: '$(Build.Repository.LocalPath)/images/AzureDevOps/ado-agents.auto.pkrvars.hcl'
          variables: 'ansible_playbook_path="$(Build.Repository.LocalPath)/images/AzureDevOps/ansible'      