---
- hosts: linux-ansible-target
  tasks:
  - include_role:
      name: linux-agent
    vars:
      install_scripts:
        - name: docker-compose
          url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_facts.system }}-{{ ansible_facts.architecture }}

      install_gpg:
        - name: docker
          url: https://download.docker.com/linux/ubuntu/gpg
          keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        - name: azure-cli
          url: https://packages.microsoft.com/keys/microsoft.asc
          keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

      install_repositories:
        # repositories that should be installed on host
        # "dest" keys denote where the repository renty is stored on filesystem
        - name: docker
          content: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable"
          filename: docker.list
        - name: azure-cli
          content: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_facts.distribution_release }} main"
          filename: azure-cli.list
          
      install_packages:
          - git
          - make
          - azure-cli
          - docker
        
    when: (ansible_facts['os_family'] | lower == "debian") or
          (ansible_facts['os_family'] | lower == "redhat")
          
  - include_role:
      name: windows-agent
    vars:
      install_packages:
        - git
        - azure-cli
    when: ansible_facts['os_family'] | lower == "windows"