---
# defaults file for linux-agent
system_packages:
  - apt-transport-https
  - build-essential
  - checkinstall
  - libreadline-gplv2-dev 
  - libncursesw5-dev 
  - libssl-dev 
  - libsqlite3-dev 
  - tk-dev 
  - libgdbm-dev 
  - libbz2-dev

install_scripts: []
download_binaries: []
install_gpg: []
install_repositories: []
install_apt_packages: []
install_from_source: []