# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main

pool:
  name: "Azure Pipelines"
  vmImage: 'ubuntu-20.04'

variables:
    # ------ Do change variables below --------
    # See "service connections" under Azure DevOps organization settings
    - name: service_connection
      value: 'azure-devops-demo-sp'

stages:
  - stage: SwapAndReplace
    jobs:
    - job: CreateImage
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'
          addToPath: true
          architecture: 'x64'
      - task: PythonScript@0
        inputs:
          scriptSource: 'filePath'
          scriptPath: '$(Build.Repository.LocalPath)/templater.py'
      - task: riezebosch.Packer.PackerTool.PackerTool@0
        displayName: 'Use Packer Latest'

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer version'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/builds/AzureDevOps/linux/blue-image.pkr.hcl'
          command: version

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer init'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/builds/AzureDevOps/linux/blue-image.pkr.hcl'
          command: init

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer validate'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/builds/AzureDevOps/linux/blue-image.pkr.hcl'
          command: validate
          variables-file: '$(Build.Repository.LocalPath)/builds/AzureDevOps/ado-agents.auto.pkrvars.hcl'
          variables: 'ansible_playbook_path=$(Build.Repository.LocalPath)/build_config'    

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer build'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/builds/AzureDevOps/linux/blue-image.pkr.hcl'
          variables-file: '$(Build.Repository.LocalPath)/builds/AzureDevOps/ado-agents.auto.pkrvars.hcl'
          variables: 'ansible_playbook_path=$(Build.Repository.LocalPath)/build_config'
          force: true

      - task: AzureCLI@2
        displayName: SwapToBlueImage
        inputs:
          azureSubscription: '$(service_connection)'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          scriptPath: '$(Build.Repository.LocalPath)/scripts/001-image-swap-vmss.sh'
          arguments: '-u -i $(Build.Repository.LocalPath)/manifest-blue.json'

      - task: riezebosch.Packer.PackerTool.PackerTool@0
        displayName: 'Use Packer Latest'

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer version'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/builds/AzureDevOps/linux/green-image.pkr.hcl'
          command: version

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer init'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/builds/AzureDevOps/linux/green-image.pkr.hcl'
          command: init

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer validate'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/builds/AzureDevOps/linux/green-image.pkr.hcl'
          command: validate
          variables-file: '$(Build.Repository.LocalPath)/builds/AzureDevOps/ado-agents.auto.pkrvars.hcl'
          variables: 'ansible_playbook_path=$(Build.Repository.LocalPath)/build_config'    

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Packer build'
        inputs:
          azureSubscription: '$(service_connection)'
          templatePath: '$(Build.Repository.LocalPath)/builds/AzureDevOps/linux/green-image.pkr.hcl'
          variables-file: '$(Build.Repository.LocalPath)/builds/AzureDevOps/ado-agents.auto.pkrvars.hcl'
          variables: 'ansible_playbook_path=$(Build.Repository.LocalPath)/build_config'
          force: true

      - task: AzureCLI@2
        displayName: SwapToGreenImage
        inputs:
          azureSubscription: '$(service_connection)'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          scriptPath: '$(Build.Repository.LocalPath)/scripts/001-image-swap-vmss.sh'
          arguments: '-u -i $(Build.Repository.LocalPath)/manifest-green.json'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.Repository.LocalPath)'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'